[datetime]
"1.7.0" = {git="https://github.com/wavebitscientific/datetime-fortran", tag="v1.7.0"}
"latest" = {git="https://github.com/wavebitscientific/datetime-fortran"}

[iso_varying_string]
"latest" = {git="https://gitlab.com/everythingfunctional/iso_varying_string"}

[jsonff]
"latest" = {git="https://gitlab.com/everythingfunctional/jsonff"}

[M_calculator]
"latest" = {git="https://github.com/urbanjost/M_calculator"}

[M_change]
"latest" = {git="https://github.com/urbanjost/M_change"}

[M_cli]
"latest" = {git="https://github.com/urbanjost/M_cli"}

[M_cli2]
"latest" = {git="https://github.com/urbanjost/M_cli2"}

[M_color]
"latest" = {git="https://github.com/urbanjost/M_color"}

[M_draw]
"latest" = {git="https://github.com/urbanjost/M_draw"}

[M_escape]
"latest" = {git="https://github.com/urbanjost/M_escape"}

[M_history]
"latest" = {git="https://github.com/urbanjost/M_history"}

[M_io]
"latest" = {git="https://github.com/urbanjost/M_io"}

[M_kracken95]
"latest" = {git="https://github.com/urbanjost/M_kracken95"}

[M_msg]
"latest" = {git="https://github.com/urbanjost/M_msg"}

[M_pixel]
"latest" = {git="https://github.com/urbanjost/M_pixel"}

[M_process]
"latest" = {git="https://github.com/urbanjost/M_process"}

[M_strings]
   "latest" = {git="https://github.com/urbanjost/M_strings"}

[M_system]
   "latest" = {git="https://github.com/urbanjost/M_system"}

[M_time]
"latest" = {git="https://github.com/urbanjost/M_time"}

[pointsets]
"latest" = {git="https://github.com/arjenmarkus/pointsets"}

[quaff]
"latest" = {git="https://gitlab.com/everythingfunctional/quaff"}

[sqliteff]
"latest" = {git="https://gitlab.com/everythingfunctional/sqliteff"}

[strff]
"latest" = {git="https://gitlab.com/everythingfunctional/strff"}

[vegetables]
"latest" = {git="https://gitlab.com/everythingfunctional/vegetables"}
