[datetime]
"1.7.0" = {git="https://github.com/wavebitscientific/datetime-fortran", tag="v1.7.0"}
"latest" = {git="https://github.com/wavebitscientific/datetime-fortran"}

[fhash]
"0.1.0" = {git="https://github.com/LKedward/fhash", tag="v0.1.0"}
"latest" = {git="https://github.com/LKedward/fhash"}

[iso_varying_string]
"latest" = {git="https://gitlab.com/everythingfunctional/iso_varying_string"}

[jsonff]
"latest" = {git="https://gitlab.com/everythingfunctional/jsonff"}

[M_calculator]
"latest" = {git="https://github.com/urbanjost/M_calculator"}

[M_change]
"latest" = {git="https://github.com/urbanjost/M_change"}

[M_cli]
"latest" = {git="https://github.com/urbanjost/M_cli"}

[M_cli2]
"latest" = {git="https://github.com/urbanjost/M_cli2"}

[M_color]
"latest" = {git="https://github.com/urbanjost/M_color"}

[M_draw]
"latest" = {git="https://github.com/urbanjost/M_draw"}

[M_escape]
"latest" = {git="https://github.com/urbanjost/M_escape"}

[M_history]
"latest" = {git="https://github.com/urbanjost/M_history"}

[M_io]
"latest" = {git="https://github.com/urbanjost/M_io"}

[M_kracken95]
"latest" = {git="https://github.com/urbanjost/M_kracken95"}

[M_msg]
"latest" = {git="https://github.com/urbanjost/M_msg"}

[M_pixel]
"latest" = {git="https://github.com/urbanjost/M_pixel"}

[M_process]
"latest" = {git="https://github.com/urbanjost/M_process"}

[M_strings]
   "latest" = {git="https://github.com/urbanjost/M_strings"}

[M_system]
   "latest" = {git="https://github.com/urbanjost/M_system"}

[M_time]
"latest" = {git="https://github.com/urbanjost/M_time"}

[mctc-gcp]
latest.git = "https://github.com/grimme-lab/gcp.git"
latest.tag = "cd69ef6"  # Debug

[mctc-lib]
latest.git = "https://github.com/grimme-lab/mctc-lib.git"
latest.tag = "61cdea0"  # Debug

[mstore]
latest.git = "https://github.com/grimme-lab/mstore.git"
latest.tag = "6896b3b"  # Debug

[pointsets]
"latest" = {git="https://github.com/arjenmarkus/pointsets"}

[quaff]
"latest" = {git="https://gitlab.com/everythingfunctional/quaff"}

[s-dftd3]
latest.git = "https://github.com/awvwgk/simple-dftd3.git"

[sqliteff]
"latest" = {git="https://gitlab.com/everythingfunctional/sqliteff"}

[strff]
"latest" = {git="https://gitlab.com/everythingfunctional/strff"}

[toml-f]
latest.git = "https://github.com/toml-f/toml-f.git"

[vegetables]
"latest" = {git="https://gitlab.com/everythingfunctional/vegetables"}
